(function() {
  var io, securityManager, securityManagerName,
    __slice = [].slice;

  io = require("./io");

  exports.print = (function(){ function _print() {
    var args, _print;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return exports.stdout.write(Array.prototype.join.call(args, " ") + "\n").flush();
  }; return _print})();

  exports.stdin = new io.TextInputStream(new io.IO(Packages.java.lang.System["in"], null));

  exports.stdout = new io.TextOutputStream(new io.IO(null, Packages.java.lang.System.out));

  exports.stderr = new io.TextOutputStream(new io.IO(null, Packages.java.lang.System.err));

  exports.args = [""].concat(global["arguments"]);

  exports.originalArgs = exports.args.slice(0);

  exports.env = global.environment || {};

  securityManager = Packages.java.lang.System.getSecurityManager();

  if (securityManager) {
    securityManagerName = securityManager.getClass().getName();
    if (/^com.google.app(engine|hosting)./.test(securityManagerName)) {
      exports.appEngine = true;
    }
    if (/^com.google.apphosting\./.test(securityManagerName)) {
      exports.appEngineHosting = true;
    }
  }

}).call(this);

// Generated by CoffeeScript 1.5.0-pre
