// Generated by CoffeeScript 1.4.0
(function() {
  var CoffeeScript, cakefileDirectory, fatalError, file, fsa0, helpers, missingTask, oparse, options, optparse, printTasks, switches, tasks;

  fsa0 = require("fs-base");

  file = require('file');

  helpers = require('./helpers');

  optparse = require('./optparse');

  CoffeeScript = require('./coffee-script');

  tasks = {};

  options = {};

  switches = [];

  oparse = null;

  helpers.extend(global, {
    task: function(name, description, action) {
      var _ref;
      if (!action) {
        _ref = [description, action], action = _ref[0], description = _ref[1];
      }
      return tasks[name] = {
        name: name,
        description: description,
        action: action
      };
    },
    option: function(letter, flag, description) {
      return switches.push([letter, flag, description]);
    },
    invoke: function(name) {
      if (!tasks[name]) {
        missingTask(name);
      }
      return tasks[name].action(options);
    }
  });

  exports.run = function() {
    var arg, args, _i, _len, _ref, _results;
    global.__originalDirname = file.canonical('.');
    fsa0.changeWorkingDirectory(cakefileDirectory(__originalDirname));
    args = global["arguments"].slice(1);
    CoffeeScript.run(file.read('Cakefile').toString(), {
      filename: 'Cakefile'
    });
    oparse = new optparse.OptionParser(switches);
    if (!args.length) {
      return printTasks();
    }
    try {
      options = oparse.parse(args);
    } catch (e) {
      return fatalError("" + e);
    }
    _ref = options["arguments"];
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      arg = _ref[_i];
      _results.push(invoke(arg));
    }
    return _results;
  };

  printTasks = function() {
    var cakefilePath, desc, name, spaces, task;
    cakefilePath = file.join(file.relative(__originalDirname, fsa0.workingDirectory()), 'Cakefile');
    system.stdout.print("" + cakefilePath + " defines the following tasks:\n");
    for (name in tasks) {
      task = tasks[name];
      spaces = 20 - name.length;
      spaces = spaces > 0 ? Array(spaces + 1).join(' ') : '';
      desc = task.description ? "# " + task.description : '';
      system.stdout.print("cake " + name + spaces + " " + desc);
    }
    if (switches.length) {
      return system.stdout.print(oparse.help());
    }
  };

  fatalError = function(message) {
    system.stderr.print(message + '\n');
    system.stdout.print('To see a list of all tasks/options, run "cake"');
    return os.exit(1);
  };

  missingTask = function(task) {
    return fatalError("No such task: " + task);
  };

  cakefileDirectory = function(dir) {
    var parent;
    if (file.exists(file.join(dir, 'Cakefile'))) {
      return dir;
    }
    parent = file.resolve(dir, '..');
    if (parent !== dir) {
      return cakefileDirectory(parent);
    }
    throw new Error("Cakefile not found in " + (fsa0.workingDirectory()));
  };

}).call(this);
