// Generated by CoffeeScript 1.5.0-pre
(function() {
  var Lexer, compile, ext, extensions, fs, lexer, loadFile, parser, path, vm, _i, _len,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
    __hasProp = {}.hasOwnProperty;

  fs = require('fs');

  path = require('path');

  Lexer = require('./lexer').Lexer;

  parser = require('./parser').parser;

  vm = require('vm');

  extensions = ['.coffee', '.litcoffee'];

  loadFile = (function(){ var _fn = function _14loadFile(module, filename) {
    var raw, stripped, _fn;
    raw = fs.readFileSync(filename, 'utf8');
    stripped = raw.charCodeAt(0) === 0xFEFF ? raw.substring(1) : raw;
    return module._compile(compile(stripped, {
      filename: filename
    }), filename);
  }; var _14loadFile = null; return _fn})();

  if (require.extensions) {
    for (_i = 0, _len = extensions.length; _i < _len; _i++) {
      ext = extensions[_i];
      require.extensions[ext] = loadFile;
    }
  }

  exports.VERSION = '1.5.0-pre';

  exports.helpers = require('./helpers');

  exports.compile = compile = (function(){ var _fn = function _15compile(code, options) {
    var header, js, merge, _fn;
    if (options == null) {
      options = {};
    }
    merge = exports.helpers.merge;
    try {
      js = (parser.parse(lexer.tokenize(code, options))).compile(options);
      if (!options.header) {
        return js;
      }
    } catch (err) {
      if (options.filename) {
        err.message = "In " + options.filename + ", " + err.message;
      }
      throw err;
    }
    header = "Generated by CoffeeScript " + this.VERSION;
    return "// " + header + "\n" + js;
  }; var _15compile = null; return _fn})();

  exports.tokens = (function(){ var _fn = function _16tokens(code, options) {
    var _fn;
    return lexer.tokenize(code, options);
  }; var _16tokens = null; return _fn})();

  exports.nodes = (function(){ var _fn = function _17nodes(source, options) {
    var _fn;
    if (typeof source === 'string') {
      return parser.parse(lexer.tokenize(source, options));
    } else {
      return parser.parse(source);
    }
  }; var _17nodes = null; return _fn})();

  exports.run = (function(){ var _fn = function _18run(code, options) {
    var mainModule, _fn, _ref;
    if (options == null) {
      options = {};
    }
    mainModule = require.main;
    mainModule.filename = process.argv[1] = options.filename ? fs.realpathSync(options.filename) : '.';
    mainModule.moduleCache && (mainModule.moduleCache = {});
    mainModule.paths = require('module')._nodeModulePaths(path.dirname(fs.realpathSync(options.filename)));
    if ((_ref = path.extname(mainModule.filename), __indexOf.call(extensions, _ref) < 0) || require.extensions) {
      return mainModule._compile(compile(code, options), mainModule.filename);
    } else {
      return mainModule._compile(code, mainModule.filename);
    }
  }; var _18run = null; return _fn})();

  exports["eval"] = function(code, options) {
    var Module, Script, js, k, o, r, sandbox, v, _j, _len1, _module, _ref, _ref1, _require;
    if (options == null) {
      options = {};
    }
    if (!(code = code.trim())) {
      return;
    }
    Script = vm.Script;
    if (Script) {
      if (options.sandbox != null) {
        if (options.sandbox instanceof Script.createContext().constructor) {
          sandbox = options.sandbox;
        } else {
          sandbox = Script.createContext();
          _ref = options.sandbox;
          for (k in _ref) {
            if (!__hasProp.call(_ref, k)) continue;
            v = _ref[k];
            sandbox[k] = v;
          }
        }
        sandbox.global = sandbox.root = sandbox.GLOBAL = sandbox;
      } else {
        sandbox = global;
      }
      sandbox.__filename = options.filename || 'eval';
      sandbox.__dirname = path.dirname(sandbox.__filename);
      if (!(sandbox !== global || sandbox.module || sandbox.require)) {
        Module = require('module');
        sandbox.module = _module = new Module(options.modulename || 'eval');
        sandbox.require = _require = (function(){ var _fn = function _19_require(path) {
          var _fn;
          return Module._load(path, _module, true);
        }; var _19_require = null; return _fn})();
        _module.filename = sandbox.__filename;
        _ref1 = Object.getOwnPropertyNames(require);
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          r = _ref1[_j];
          if (r !== 'paths') {
            _require[r] = require[r];
          }
        }
        _require.paths = _module.paths = Module._nodeModulePaths(process.cwd());
        _require.resolve = (function(){ var _fn = function _20resolve(request) {
          var _fn;
          return Module._resolveFilename(request, _module);
        }; var _20resolve = null; return _fn})();
      }
    }
    o = {};
    for (k in options) {
      if (!__hasProp.call(options, k)) continue;
      v = options[k];
      o[k] = v;
    }
    o.bare = true;
    js = compile(code, o);
    if (sandbox === global) {
      return vm.runInThisContext(js);
    } else {
      return vm.runInContext(js, sandbox);
    }
  };

  lexer = new Lexer;

  parser.lexer = {
    lex: (function(){ var _fn = function _21lex() {
      var tag, _fn, _ref;
      _ref = this.tokens[this.pos++] || [''], tag = _ref[0], this.yytext = _ref[1], this.yylineno = _ref[2];
      return tag;
    }; var _21lex = null; return _fn})(),
    setInput: (function(){ var _fn = function _22setInput(tokens) {
      var _fn;
      this.tokens = tokens;
      return this.pos = 0;
    }; var _22setInput = null; return _fn})(),
    upcomingInput: (function(){ var _fn = function _23upcomingInput() {
      var _fn;
      return "";
    }; var _23upcomingInput = null; return _fn})()
  };

  parser.yy = require('./nodes');

}).call(this);
