// Generated by CoffeeScript 1.5.0-pre
(function() {
  var extend, flatten, _ref;

  exports.starts = (function(){ var _fn = function _54starts(string, literal, start) {
    var _fn;
    return literal === string.substr(start, literal.length);
  }; var _54starts = null; return _fn})();

  exports.ends = (function(){ var _fn = function _55ends(string, literal, back) {
    var len, _fn;
    len = literal.length;
    return literal === string.substr(string.length - len - (back || 0), len);
  }; var _55ends = null; return _fn})();

  exports.compact = (function(){ var _fn = function _56compact(array) {
    var item, _fn, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = array.length; _i < _len; _i++) {
      item = array[_i];
      if (item) {
        _results.push(item);
      }
    }
    return _results;
  }; var _56compact = null; return _fn})();

  exports.count = (function(){ var _fn = function _57count(string, substr) {
    var num, pos, _fn;
    num = pos = 0;
    if (!substr.length) {
      return 1 / 0;
    }
    while (pos = 1 + string.indexOf(substr, pos)) {
      num++;
    }
    return num;
  }; var _57count = null; return _fn})();

  exports.merge = (function(){ var _fn = function _58merge(options, overrides) {
    var _fn;
    return extend(extend({}, options), overrides);
  }; var _58merge = null; return _fn})();

  extend = exports.extend = (function(){ var _fn = function _59extend(object, properties) {
    var key, val, _fn;
    for (key in properties) {
      val = properties[key];
      object[key] = val;
    }
    return object;
  }; var _59extend = null; return _fn})();

  exports.flatten = flatten = (function(){ var _fn = function _60flatten(array) {
    var element, flattened, _fn, _i, _len;
    flattened = [];
    for (_i = 0, _len = array.length; _i < _len; _i++) {
      element = array[_i];
      if (element instanceof Array) {
        flattened = flattened.concat(flatten(element));
      } else {
        flattened.push(element);
      }
    }
    return flattened;
  }; var _60flatten = null; return _fn})();

  exports.del = (function(){ var _fn = function _61del(obj, key) {
    var val, _fn;
    val = obj[key];
    delete obj[key];
    return val;
  }; var _61del = null; return _fn})();

  exports.last = (function(){ var _fn = function _62last(array, back) {
    var _fn;
    return array[array.length - (back || 0) - 1];
  }; var _62last = null; return _fn})();

  exports.some = (_ref = Array.prototype.some) != null ? _ref : function(fn) {
    var e, _i, _len;
    for (_i = 0, _len = this.length; _i < _len; _i++) {
      e = this[_i];
      if (fn(e)) {
        return true;
      }
    }
    return false;
  };

}).call(this);
